//
//  SelectCountriesModels.swift
//  CleanSwiftSample
//
//  Created by Ali Samaiee on 8/10/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SelectCountries {
  // MARK: Use cases
    struct Request {
        struct Fetch {
            /// filter: will only show countries containing 'filter' in their names, empty string means no filter
            let filter: String
        }

        struct ToggleSelected {
            let key: String
        }
    }
    
    struct Response {
        struct FetchCountry {
            struct Country {
                let name: String
                var selected: Bool
            }
            let countries: [Country]?
            let error: Error?
        }

        struct ToggleCountry {
            let name: String
            let selected: Bool
            let success : Bool
            let error : Error?
        }
    }

    struct ViewModel {
        struct Country {
            let title: String
            var selected: Bool
        }

        /// To update whole data
        struct ReloadCountries {
            var countries: [Country]
        }
    }
}
