//
//  CountriesWorker.swift
//  CleanSwiftSample
//
//  Created by Ali Samaiee on 8/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CountriesWorker {
    let memoryDataProvider: CountryMemoryDataProvider
    
    init(countryMemoryProvider: CountryMemoryDataProvider) {
        self.memoryDataProvider = countryMemoryProvider
    }
    
    func getCountries() -> [Countries.Response.Country]? {
        let allCountries = self.memoryDataProvider.getAll()
        switch allCountries {
        case .Success(let countries):
            let response = countries.map { Countries.Response.Country(name: $0.name, selected: $0.selected) }
            return response
        case .Failed(let error):
            Logger.printToConsole("CountriesWorker -> getSelectedCountries: getting data failed with error \(error)")
            return nil
        }
    }
}
