//
//  CountriesModels.swift
//  CleanSwiftSample
//
//  Created by Ali Samaiee on 8/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Countries {
    struct Response {
        struct Country {
            var name: String
            var selected: Bool
        }
    }
    struct ViewModel {
        let countries: [String]
    }
}
