//
//  CountriesPresenter.swift
//  CleanSwiftSample
//
//  Created by Ali Samaiee on 8/9/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountriesPresentationLogic {
    func presentSelectedCountries(response: [Countries.Response.Country])
}

class CountriesPresenter: CountriesPresentationLogic {
    weak var viewController: CountriesDisplayLogic?
    
    func presentSelectedCountries(response: [Countries.Response.Country]) {
        let countries = response.map { $0.name }
        let viewModel = Countries.ViewModel(countries: countries)
        DispatchQueue.main.async {
            self.viewController?.updateTextView(withData: viewModel)
        }
    }
}
